import Head from 'next/head'

import Dashboard from '../components/Dashboard'

export default function Home() {
  return (
    <>
      <Head>
        <title>Social media dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        // displays site properly based on user's device
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />
      </Head>

      <main>
        <div className='bg'></div>
        <Dashboard />
      </main>

      <footer>
        <div className='attribution'>
          Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>. 
          Coded by <a href="#">Tomwf</a>.
        </div>
      </footer>
    </>
  )
}
