import Head from 'next/head'
import Image from 'next/image'
import  { ThemeProvider } from 'styled-components'

import theme from '../theme/theme'
import Title from '../components/Title'
import Subtitle from '../components/Subtitle'
import HorizontalLine from '../components/HorizontalLine'
import ThemeToggle from '../components/ThemeToggle'


export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Frontend Mentor | [Challenge Name Here]</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="UTF-8" />
        // displays site properly based on user's device
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />
      </Head>

      <main>
        <div>
          <Title text="Social Media Dashboard" />
          <Subtitle text="Total Followers: 23,004" />
          <HorizontalLine />
          <ThemeToggle>
            <Subtitle text="Dark mode" />
            <div>
              <input type="checkbox" />
              <span></span>
            </div>
          </ThemeToggle>
        </div>

        <div>
          <div>
            <div>
              <a href="">@nathanf</a>
              <span>1987</span>
              <span>Followers</span>
              <p><span>12</span> Today</p>
            </div>
          </div>

          <div>
            <div>
              <a href="">@nathanf</a>
              <span>1044</span>
              <span>Followers</span>
              <p><span>99</span> Today</p>
            </div>
          </div>

          <div>
            <div>
              <a href="">@realnathanf</a>
              <span>11k</span>
              <span>Followers</span>
              <p><span>1099</span> Today</p>
            </div>
          </div>

          <div>
            <div>
              <a href="">Nathan F.</a>
              <span>8239</span>
              <span>Subscribers</span>
              <p><span>144</span> Today</p>
            </div>
          </div>
        </div>

        <h2>Overview - Today</h2>
        <div>
          <div>
            <div>
              <span>Page Views</span>
              <span></span>
            </div>
            <div>
              <span>87</span>
              <span>3</span>
            </div>
          </div>

          <div>
            <div>
              <span>Likes</span>
              <span></span>
            </div>
            <div>
              <span>52</span>
              <span>2</span>
            </div>
          </div>

          <div>
            <div>
              <span>Likes</span>
              <span></span>
            </div>
            <div>
              <span>5462</span>
              <span>2257</span>
            </div>
          </div>

          <div>
            <div>
              <span>Profile Views</span>
              <span></span>
            </div>
            <div>
              <span>52k</span>
              <span>1375</span>
            </div>
          </div>

          <div>
            <div>
              <span>Retweets</span>
              <span></span>
            </div>
            <div>
              <span>117</span>
              <span>303</span>
            </div>
          </div>

          <div>
            <div>
              <span>Likes</span>
              <span></span>
            </div>
            <div>
              <span>507</span>
              <span>553</span>
            </div>
          </div>

          <div>
            <div>
              <span>Likes</span>
              <span></span>
            </div>
            <div>
              <span>107</span>
              <span>19</span>
            </div>
          </div>

          <div>
            <div>
              <span>Total Views</span>
              <span></span>
            </div>
            <div>
              <span>1407</span>
              <span>12</span>
            </div>
          </div>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </ThemeProvider>
  )
}
