import Head from 'next/head'

import Dashboard from '../components/Dashboard'

export default function Home() {
  return (
    <>
      <Head>
        <title>Social media dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <main>
        <div className='bg'></div>
        <Dashboard />
      </main>

      <footer>
        <div className='attribution'>
          Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank" rel="noreferrer">Frontend Mentor</a>. 
          Coded by <a href="#">Tomwf</a>.
        </div>
      </footer>
    </>
  )
}
